#!/bin/sh
echo
echo -e "\033[32mSystem init\033[0;1m"
#sleep 2
# If we mount run volatily, the anopa initrd loses itself
#mount -t tmpfs none /run
# Only mount proc if it isn't yet mounted. For example, an iso boot's
# initramfs will pre-mount this before we are called.
if [ ! -e /proc/1 ]; then
    mount -t proc proc /proc
fi
if [ ! -e /sys/kernel ]; then
    mount -t sysfs sys /sys
fi
# Our builder can't handle having FIFOs yet, so we'll make it ourselves if it
# doesn't exist yet
if [ ! -e /etc/anopa/services/uncaught-logs/fifo ]; then
    mkfifo /etc/anopa/services/uncaught-logs/fifo
fi
mount -t tmpfs none /var/volatile
mkdir /var/volatile/log
mkdir /var/volatile/log/boot
if aa-incmdline debstage0; then
    exec /bin/sh
fi
exec /libexec/aa-stage1
# Just incase above exec fails, fall back to a shell
exec /bin/sh
