require s6-linux-init-1.inc

LIC_FILES_CHKSUM = "file://COPYING;md5=4116b5d84e17386dbe68724294cd8933"

SRC_URI[md5sum] = "ff97a1914f4f8d4e7973d0dc6f2bcc39"
SRC_URI[sha256sum] = "978c38fe71f3d2fb44c455f2f911b409a87a384c2e14b1eb1ef138e21a956bbe"

# 0.2.0.0 needs skalibs >= 2.4.0.0
# It builds a system needing (at boot):
#   execline >= 2.2.0.0
#   s6-portable-utils >= 2.1.0.0
#   s6-linux-utils >= 2.2.0.0
#   s6 >= 2.4.0.0

# 0.3.0.0 needs skalibs >= 2.5.0.0,
#    execline >= 2.3.0.0,
#    s6-portable-utils >= 2.2.0.0, 
#    s6-linux-utils >= 2.3.0.0,
#    s6 >= 2.5.0.0

# 0.3.1.1 needs skalibs >= 2.6.0.0,
#    execline >= 2.3.0.2,
#    s6-portable-utils >= 2.2.1.1, 
#    s6-linux-utils >= 2.4.0.0,
#    s6 >= 2.6.1.0

# 0.4.0.0 needs skalibs >= 2.6.4.0,
#    execline >= 2.3.0.4,
#    s6-portable-utils >= 2.2.1.1, 
#    s6-linux-utils >= 2.4.0.2,
#    s6 >= 2.7.1.0
#    old rc.shutdown is now autogenerated
#    rc.tini is now named (new) rc.shutdown
#
# 1.0.5.1 needs
#   skalibs >= 2.9.3.0
#   execline >= 2.6.1.1
#   s6 >= 2.9.2.0
#   optionally nss >= 0.0.2.2 (if using musl)
#   optionally utmps >= 0.0.3.2
