require s6-linux-init.inc

LIC_FILES_CHKSUM = "file://COPYING;md5=76d6194d4039114189edef052ff98418"

SRC_URI[md5sum] = "4b1c183e30728b1126a223c5a839bc32"
SRC_URI[sha256sum] = "d4ac9b8bde3e678353c85dad1a2a25066a40f843c53840c4210839068635ed7e"

# 0.2.0.0 needs skalibs >= 2.4.0.0
# It builds a system needing (at boot):
#   execline >= 2.2.0.0
#   s6-portable-utils >= 2.1.0.0
#   s6-linux-utils >= 2.2.0.0
#   s6 >= 2.4.0.0

# 0.3.0.0 needs skalibs >= 2.5.0.0,
#    execline >= 2.3.0.0,
#    s6-portable-utils >= 2.2.0.0, 
#    s6-linux-utils >= 2.3.0.0,
#    s6 >= 2.5.0.0

# 0.3.1.1 needs skalibs >= 2.6.0.0,
#    execline >= 2.3.0.2,
#    s6-portable-utils >= 2.2.1.1, 
#    s6-linux-utils >= 2.4.0.0,
#    s6 >= 2.6.1.0

# 0.4.0.0 needs skalibs >= 2.6.4.0,
#    execline >= 2.3.0.4,
#    s6-portable-utils >= 2.2.1.1, 
#    s6-linux-utils >= 2.4.0.2,
#    s6 >= 2.7.1.0
#    old rc.shutdown is now autogenerated
#    rc.tini is now named (new) rc.shutdown
